project:
  type: manuscript

manuscript:
  article: index.qmd
  notebooks:
    - notebooks/scatterplots.qmd
    - notebooks/dependence.qmd
    - notebooks/gee_app.qmd
    - notebooks/code_models.ipynb
    - notebooks/code_scatterplots.ipynb

format:
  html:
    comments:
      hypothesis: true
  docx: default
  jats: default
  pdf: default

  # (other formats)
  # pdf: default

execute:
  freeze: true

editor: visual

